# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: metrics
on:
  schedule:
    - cron: "15 05 1 * *"
  workflow_dispatch:

# Takes time so we do it on schedule only rather than on push.
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@65836723097537a54cd8eb90f61839426b4266b6 # v3.34
        id: lowlighter_metrics
        name: Generate Metrics SVG
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: github-metrics.svg
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
